dist: jammy
sudo: false
language: python
jobs:
  include:
    - stage: test
      if: tag IS blank
      python:
        - "3.12"
      before_install:
        - pip install -U setuptools poetry
      install:
        - poetry install
      script:
        - poetry run make lint
        - poetry run make test
        - poetry run make security
