os: linux
dist: jammy
language: python
python:
- '3.12'
branches:
  only:
  - master
before_install:
- pip install -U setuptools poetry
install:
- poetry install
jobs:
  include:
  - stage: test
    if: tag IS blank
    script:
    - poetry run make lint
    - poetry run make test
    - poetry run make security
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: LJoJiHlInJ0pVKvli7H7mDqGg7Y+2L0rC79yKd4v02zJwEkDT4Y9XcjUbe7l/lctpPGwyJ+o2756TWqC9Lcsj/kaC6bFTq8JxuCGWaNAxS7E9cARi3y4Y4ovXAz+l9APRxZ9z1rM0hVLZhnjTetz/t02hpJrKLO4Jgy7aS4VOLl2TA1gTMx7Agjje41Fl0z1Ep/FXDCcgM7uxCmQHykSx54vXMq+nEgkhxr9/TIh4RigEly6eex3OSX8KHW4cufnU43otJL0qGhgRqdGH6xpA0wFPJf3PRtscQvp8g8VQIpe+MsFWaYRna3NRicO69SBoH0hjxhcKalZ3SSL/xHSP19BFtUbadyLOt4UdUM1/Lz0jR6RR882pLQGaOIMI1UG0QVKrLYWL6CqEOd85hbv0Cdz9qnd8ZwoDAEeekSv4RMyDKHp3k5NcNQmuX99xiWw+3B00R+58ONmI0DbaJjcTXDB7HZShXmY2KAiN+5q39mo8g+5oIyzN3DS0qiqLCrtJ3A2Hz4qmGH3GjbRpJALtBHFGyYrZWHp8lMki4p5w8+Yim6UAhRIIJRiNC0CEeqEF0YbO/VVi2c+RgEckxCDl7LWwl6yu4uS5TzrDnGvk+zGggPgxMmAKU52f8uPjDCUzdBoTmoP85UI6uzqmr7CeqqtHhe/yhNtgYOHeuhPQ4o=
  on:
    tags: true
    repo: sdelements/depocs
