name: dev

on:
  push:
    branches:
      - develop
      - master
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools poetry
          poetry install
      - name: lint
        run: |
          isort .
          black .
          flake8 . --extend-ignore=D,E501,W601 --extend-exclude=docs/ --statistics --count
      - name: security
        run: bandit -c pyproject.toml -r .
      - name: test
        run: python -m unittest discover
